"""Add irrigation and sensor models

Revision ID: 8192b084bc84
Revises: e72cdd932dd7
Create Date: 2026-05-13 23:51:17.706102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from config.database_types import UUID


# revision identifiers, used by Alembic.
revision: str = '8192b084bc84'
down_revision: Union[str, None] = 'e72cdd932dd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('irrigation_schedules',
    sa.Column('id', UUID(), nullable=False),
    sa.Column('zone_id', UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('repeat_days', sa.String(length=50), nullable=True),
    sa.Column('water_amount', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('irrigation_logs',
    sa.Column('id', UUID(), nullable=False),
    sa.Column('schedule_id', UUID(), nullable=False),
    sa.Column('zone_id', UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('water_used', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['irrigation_schedules.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor_readings',
    sa.Column('id', UUID(), nullable=False),
    sa.Column('sensor_id', UUID(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('is_alert', sa.Boolean(), nullable=True),
    sa.Column('alert_message', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('sensors', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('sensors', sa.Column('type', sa.String(length=50), nullable=False))
    op.add_column('sensors', sa.Column('is_active', sa.String(length=20), nullable=True))
    op.drop_index('ix_sensors_device_id', table_name='sensors')
    op.drop_column('sensors', 'status')
    op.drop_column('sensors', 'battery_level')
    op.drop_column('sensors', 'calibration_date')
    op.drop_column('sensors', 'last_seen')
    op.drop_column('sensors', 'sensor_type')
    op.drop_column('sensors', 'device_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensors', sa.Column('device_id', sa.VARCHAR(length=100), nullable=False))
    op.add_column('sensors', sa.Column('sensor_type', sa.VARCHAR(length=20), nullable=False))
    op.add_column('sensors', sa.Column('last_seen', sa.DATETIME(), nullable=True))
    op.add_column('sensors', sa.Column('calibration_date', sa.DATETIME(), nullable=True))
    op.add_column('sensors', sa.Column('battery_level', sa.INTEGER(), nullable=True))
    op.add_column('sensors', sa.Column('status', sa.VARCHAR(length=20), nullable=True))
    op.create_index('ix_sensors_device_id', 'sensors', ['device_id'], unique=1)
    op.drop_column('sensors', 'is_active')
    op.drop_column('sensors', 'type')
    op.drop_column('sensors', 'name')
    op.drop_table('sensor_readings')
    op.drop_table('irrigation_logs')
    op.drop_table('irrigation_schedules')
    # ### end Alembic commands ###
